### ISSUE TITLE
Can turn devices off but not on

### ISSUE THREAD

**Issue by wilvancleve** [jeubanks/hubitat-mqtt-bridge#3]
First, thanks for this library. I'm so close to perfectly happy here that I can taste it, but something is off, and I can't tell exactly what.

I'm working on a single switch. My HA install is updated by changes of Hubitat state. When the switch is **on**, I can turn it **off** from HA, and see the MQTT messages (in both the bridge, an MQTT client, and in the Hubitat logs). When the switch is **off**, I cannot successfully turn it on in HA (or by publishing a request in MQTT). The message is sent from HA to MQTT, but it does not appear in the Hubitat logs for the Bridge App, the Bridge Device, or the switch, and the light does not turn on.

It would seem to me that the issue here is in the way the Bridge App is processing the on payload for the switch, but I can't figure out why that would be.

Here's the relevant section of my HA config

```
switch:
  - platform: mqtt
    name: "Outside Light"
    state_topic: "hubitat/Outside Light/switch/state"
    command_topic: "hubitat/Outside Light/switch/cmd"
    payload_on: "on"
    payload_off: "off"
    retain: true

```

And here's my mqtt bridge config

`mqtt:
    # Specify your MQTT Broker's hostname or IP address here
    host: 192.168.164.2
    preface: hubitat

    state_read_suffix: state
    state_write_suffix: set_state

    command_suffix: cmd

# Port number to listen on
port: 8080
`
Googling indicates to me that I'm not the first person to have a problem between off and on.
