### ISSUE TITLE
Events sent to Locks don't seem to work

### ISSUE THREAD

**Issue by CWSpear** [jeubanks/hubitat-mqtt-bridge#8]
I can see that `hubitat/Front Door Lock/lock = unlocked` is getting published when I trigger it in Home Assistant, but the lock is still locked.

Updates from Hubitat to Home Assistant work (unlocking it manually).

This is my Lock config:

```yaml
- platform: mqtt
  name: Front Door Lock
  state_topic: hubitat/Front Door Lock/lock
  command_topic: hubitat/Front Door Lock/lock
  payload_lock: locked
  payload_unlock: unlocked
  state_locked: locked
  state_unlocked: unlocked
  optimistic: false
  qos: 1
  retain: true
```

I have a **Schlage BE468/BE469 Lock**.

When I press it in Home Assistant, I can see it in the MQTT Bridge Device Event log:

```
{"name":"Front Door Lock","type":"lock","value":"unlocked","command":true}
```

So I know the MQTT command is getting the event... it's a breakdown somewhere between there and actually unlocking the door (e.g. either the Zwave command isn't even being called, or else it's being rejected).

It does not work to unlock nor lock the door.

**Comment by CWSpear** [comment]
Ok, so the App is looking for `lock` and `unlock` payloads, whereas the event for when it un/locks is `locked` and `unlocked`, so this change:

```
-  payload_lock: locked
-  payload_unlock: unlocked
+  payload_lock: lock
+  payload_unlock: unlock
```

with the final result of:

```yaml
- platform: mqtt
  name: Front Door Lock
  state_topic: hubitat/Front Door Lock/lock
  command_topic: hubitat/Front Door Lock/lock
  payload_lock: lock
  payload_unlock: unlock
  state_locked: locked
  state_unlocked: unlocked
  optimistic: false
  qos: 1
  retain: true
```

made it work.

I was coming from SmartThings, which [uses `unlocked`/`locked`](https://github.com/stjohnjohnson/smartthings-mqtt-bridge/blob/066d3f492e2f9d9016964bef191230b99cb4e0c8/smartapps/stj/mqtt-bridge.src/mqtt-bridge.groovy#L725-L731) for both the state and payload, which is why I was confident it should have worked! :)

If we really wanted to be thorough, we could make the app support both with and without `-ed` for the command... but the way you have it also makes sense ([no `-ed` for the payload is even the default (but state has the `-ed`)](https://www.home-assistant.io/integrations/lock.mqtt/)... if I'd just done nothing in terms of defining the payload/state, it would have worked!)
